before_script:
   - npm-cache install
job:
   script:
      - gulp
      - gulp build:zip
      - rsync -avzr --stats --delete-after --exclude 'node_modules' --exclude 'assets/src' --exclude '.*' --exclude '.*/' ./dist/ deployer@demos.pixel2html.com:/home/deployer/www/demos/000/000Pixel2HTML Frontend test/
      - "curl -X POST -F path=000/000Pixel2HTML Frontend test http://deployer.pixel2html.com/html/demo_links_update"
